In [1]:
import pandas as pd
import numpy as np
from datetime import datetime as dt

In [2]:
data = pd.read_csv("/content/status.csv")
data

orderId    status
0          1  status_b
1          2  status_b
2          3  status_a
3          4  status_a
4          5  status_b
..       ...       ...
265      266  status_b
266      267  status_b
267      268  status_a
268      269  status_b
269      270  status_a

[270 rows x 2 columns]

In [3]:
data.isnull().sum()

orderId    0
status     0
dtype: int64

In [4]:
data.status.unique()

array(['status_b', 'status_a'], dtype=object)

In [5]:
data1 = pd.read_csv("/content/status_details.csv")
data1


Timestamp  orderId  distributorId  originalDistributorId  hubId  \
0       13/09/22 2:30       49              1                    1.0    1.0   
1       13/09/22 2:30      203              1                    1.0    1.0   
2       13/09/22 2:30      143              1                    1.0    1.0   
3       13/09/22 2:30      118              1                    1.0    1.0   
4       13/09/22 2:30      167              1                    1.0    1.0   
...               ...      ...            ...                    ...    ...   
11796  13/09/22 13:48      211             14                   30.0    4.0   
11797  13/09/22 13:48       81             14                   28.0    4.0   
11798  13/09/22 13:48       96             14                   43.0    4.0   
11799  13/09/22 13:48      237             14                   33.0    4.0   
11800  13/09/22 14:42      172             14                   44.0    4.0   

       quantity    Amount hubCode  Unnamed: 8  Unnamed: 9  Unnamed: 10  \
0             4    555.04       a         NaN         NaN          NaN   
1             4    851.04       a         NaN         NaN          NaN   
2             1   1137.64       a         NaN         NaN          NaN   
3             3    859.92       a         NaN         NaN          NaN   
4             6  11453.20       a         NaN         NaN          NaN   
...         ...       ...     ...         ...         ...          ...   
11796       480  82980.10       f         NaN         NaN          NaN   
11797       600   8941.36       f         NaN         NaN          NaN   
11798        20  14029.02       f         NaN         NaN          NaN   
11799       100  42836.10       f         NaN         NaN          NaN   
11800        12   3991.98       f         NaN         NaN          NaN   

       Unnamed: 11  Unnamed: 12  Unnamed: 13  Unnamed: 14  
0              NaN          NaN          NaN          NaN  
1              NaN          NaN          NaN          NaN  
2              NaN          NaN          NaN          NaN  
3              NaN          NaN          NaN          NaN  
4              NaN          NaN          NaN          NaN  
...            ...          ...          ...          ...  
11796          NaN          NaN          NaN          NaN  
11797          NaN          NaN          NaN          NaN  
11798          NaN          NaN          NaN          NaN  
11799          NaN          NaN          NaN          NaN  
11800          NaN          NaN          NaN          NaN  

[11801 rows x 15 columns]

In [6]:
data1.columns

Index(['Timestamp', 'orderId', 'distributorId', 'originalDistributorId',
       'hubId', 'quantity', 'Amount', 'hubCode', 'Unnamed: 8', 'Unnamed: 9',
       'Unnamed: 10', 'Unnamed: 11', 'Unnamed: 12', 'Unnamed: 13',
       'Unnamed: 14'],
      dtype='object')

In [7]:
data1.drop('Unnamed: 8',axis='columns',inplace = True)
data1.drop('Unnamed: 9',axis='columns',inplace = True)
data1.drop('Unnamed: 10',axis='columns',inplace = True)
data1.drop('Unnamed: 11',axis='columns',inplace = True)
data1.drop('Unnamed: 12',axis='columns',inplace = True)
data1.drop('Unnamed: 13',axis='columns',inplace = True)
data1.drop('Unnamed: 14',axis='columns',inplace = True)

In [8]:
data1.head()

Timestamp  orderId  distributorId  originalDistributorId  hubId  \
0  13/09/22 2:30       49              1                    1.0    1.0   
1  13/09/22 2:30      203              1                    1.0    1.0   
2  13/09/22 2:30      143              1                    1.0    1.0   
3  13/09/22 2:30      118              1                    1.0    1.0   
4  13/09/22 2:30      167              1                    1.0    1.0   

   quantity    Amount hubCode  
0         4    555.04       a  
1         4    851.04       a  
2         1   1137.64       a  
3         3    859.92       a  
4         6  11453.20       a

In [9]:
data1.isnull().sum()

Timestamp                 0
orderId                   0
distributorId             0
originalDistributorId    18
hubId                    18
quantity                  0
Amount                    0
hubCode                   0
dtype: int64

In [10]:
data1.originalDistributorId .unique()

array([ 1., nan,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 33., 34., 35., 36., 15., 16., 17., 18., 19., 37., 38., 39.,
       20., 21., 40., 22., 14., 23., 24., 25., 26., 27., 41., 42., 28.,
       29., 30., 31., 32., 43., 44.])

In [11]:
data1.hubId.unique()

array([ 1., nan,  2.,  4.])

In [12]:
data1.hubId.dropna()

0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
        ... 
11796    4.0
11797    4.0
11798    4.0
11799    4.0
11800    4.0
Name: hubId, Length: 11783, dtype: float64

In [13]:
data1.isnull().sum()

Timestamp                 0
orderId                   0
distributorId             0
originalDistributorId    18
hubId                    18
quantity                  0
Amount                    0
hubCode                   0
dtype: int64

In [14]:
data1['hubId'] = data1['hubId'].fillna(data1['hubId'].mode()[0])
data1['originalDistributorId'] = data1['originalDistributorId'].fillna(data1['originalDistributorId'].mode()[0])


In [15]:
data1.isnull().sum()

Timestamp                0
orderId                  0
distributorId            0
originalDistributorId    0
hubId                    0
quantity                 0
Amount                   0
hubCode                  0
dtype: int64

In [16]:
data1["Timestamp"]= pd.to_datetime(data1["Timestamp"])

In [17]:
data1['hour']=data1['Timestamp'].dt.hour

In [18]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11801 entries, 0 to 11800
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   Timestamp              11801 non-null  datetime64[ns]
 1   orderId                11801 non-null  int64         
 2   distributorId          11801 non-null  int64         
 3   originalDistributorId  11801 non-null  float64       
 4   hubId                  11801 non-null  float64       
 5   quantity               11801 non-null  int64         
 6   Amount                 11801 non-null  float64       
 7   hubCode                11801 non-null  object        
 8   hour                   11801 non-null  int64         
dtypes: datetime64[ns](1), float64(3), int64(4), object(1)
memory usage: 829.9+ KB


In [19]:
data1.head()

Timestamp  orderId  distributorId  originalDistributorId  hubId  \
0 2022-09-13 02:30:00       49              1                    1.0    1.0   
1 2022-09-13 02:30:00      203              1                    1.0    1.0   
2 2022-09-13 02:30:00      143              1                    1.0    1.0   
3 2022-09-13 02:30:00      118              1                    1.0    1.0   
4 2022-09-13 02:30:00      167              1                    1.0    1.0   

   quantity    Amount hubCode  hour  
0         4    555.04       a     2  
1         4    851.04       a     2  
2         1   1137.64       a     2  
3         3    859.92       a     2  
4         6  11453.20       a     2

In [20]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 11801 entries, 0 to 11800
Data columns (total 9 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   Timestamp              11801 non-null  datetime64[ns]
 1   orderId                11801 non-null  int64         
 2   distributorId          11801 non-null  int64         
 3   originalDistributorId  11801 non-null  float64       
 4   hubId                  11801 non-null  float64       
 5   quantity               11801 non-null  int64         
 6   Amount                 11801 non-null  float64       
 7   hubCode                11801 non-null  object        
 8   hour                   11801 non-null  int64         
dtypes: datetime64[ns](1), float64(3), int64(4), object(1)
memory usage: 829.9+ KB


In [21]:
data1.hour.unique()

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [22]:
data1.drop('Timestamp',axis='columns',inplace = True)

In [23]:
## now merage both datafram

df = pd.merge(data,data1, on='orderId')
df

orderId    status  distributorId  originalDistributorId  hubId  \
0            1  status_b              1                    1.0    1.0   
1            1  status_b              1                    1.0    1.0   
2            1  status_b              1                    1.0    1.0   
3            1  status_b              2                    2.0    1.0   
4            1  status_b              2                    2.0    1.0   
...        ...       ...            ...                    ...    ...   
11796      270  status_a             27                   27.0    1.0   
11797      270  status_a             15                   15.0    1.0   
11798      270  status_a              8                    8.0    2.0   
11799      270  status_a              5                    5.0    1.0   
11800      270  status_a              2                    2.0    1.0   

       quantity    Amount hubCode  hour  
0            13   1487.04       a     2  
1             7   1205.58       a     2  
2             2    535.50       a     2  
3             2    377.91       a     2  
4            10    420.45       a     2  
...         ...       ...     ...   ...  
11796      1800  50085.00       a    10  
11797         6   6022.59       a    11  
11798         1    652.47       b    11  
11799        16   2290.88       a    12  
11800         2     55.92       a    12  

[11801 rows x 9 columns]

In [24]:
a1=df['quantity'].groupby(df['hour']).count()
a1

hour
2     2280
3      873
4      644
5      557
6      853
7     1298
8     1491
9     1192
10      98
11     543
12    1941
13      30
14       1
Name: quantity, dtype: int64

In [25]:
df1 = pd.DataFrame(a1)
df1

quantity
hour          
2         2280
3          873
4          644
5          557
6          853
7         1298
8         1491
9         1192
10          98
11         543
12        1941
13          30
14           1

In [26]:
df1.rename({'quantity':'odercount'},axis=1, inplace=True)
df1


odercount
hour           
2          2280
3           873
4           644
5           557
6           853
7          1298
8          1491
9          1192
10           98
11          543
12         1941
13           30
14            1

In [27]:
df1.to_csv("1.csv")

In [28]:
df2= df[["distributorId","originalDistributorId"]]
df2.to_csv('2.csv')
df2


distributorId  originalDistributorId
0                  1                    1.0
1                  1                    1.0
2                  1                    1.0
3                  2                    2.0
4                  2                    2.0
...              ...                    ...
11796             27                   27.0
11797             15                   15.0
11798              8                    8.0
11799              5                    5.0
11800              2                    2.0

[11801 rows x 2 columns]

In [29]:
df6= df[["hubId"]]
df6.to_csv('6.csv')
df6

hubId
0        1.0
1        1.0
2        1.0
3        1.0
4        1.0
...      ...
11796    1.0
11797    1.0
11798    2.0
11799    1.0
11800    1.0

[11801 rows x 1 columns]

In [30]:
df7= df[["hubCode","distributorId"]]
df7.to_csv('7.csv')
df7

hubCode  distributorId
0           a              1
1           a              1
2           a              1
3           a              2
4           a              2
...       ...            ...
11796       a             27
11797       a             15
11798       b              8
11799       a              5
11800       a              2

[11801 rows x 2 columns]